import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
// import { Manrope } from "next/font/google";
// import { Variable } from "lucide-react";
// import { ElmessSans } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});

// ${geistSans.variable} ${geistMono.variable}


// const elmsSans = ElmessSans({
//   subsets: ["latin"],
//   variable: "--font-elms-sans",
//   weight: ["400", "500", "600", "700", "800", "900"], // customize if needed
// });
export const metadata: Metadata = {
  title: "Adekunle Adebona",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
